package services;

import database.ComandaDAO;
import database.SoferDAO;
import models.Client;
import models.Comanda;
import models.Plata;
import models.Produs;
import models.Restaurant;
import models.Sofer;
import java.util.ArrayList;
import java.util.List;

public class OrderService {
    private List<Comanda> comenzi = new ArrayList<>();

    private final ComandaDAO comandaDAO = new ComandaDAO();
    private final SoferDAO soferDAO = new SoferDAO();
    private final AuditService audit = AuditService.getInstance();

    public Comanda plaseazaComanda(Client client, Restaurant restaurant, List<Produs> produse) {
        Comanda comanda = new Comanda(client, restaurant, produse);
        comenzi.add(comanda);
        comandaDAO.create(comanda); // INSERT -> sets the id generated by the DB
        System.out.println("\nComanda #" + comanda.getId() + " a fost plasata cu succes de " + client.getNume());
        audit.logActiune("plaseazaComanda");
        return comanda;
    }

    public void proceseazaPlata(Comanda comanda, String metoda) {
        double total = comanda.calculeazaTotal();
        Plata plata = new Plata(total, metoda);
        comanda.setPlata(plata);
        comandaDAO.update(comanda); // UPDATE: save the payment on the order
        System.out.println("Plata in valoare de " + total + " RON a fost procesata (" + metoda + ").");
        audit.logActiune("proceseazaPlata");
    }

    // the driver is passed in from outside (from UserService)
    public void alocaSofer(Comanda comanda, Sofer sofer) {
        if (sofer != null) {
            comanda.setSoferAsignat(sofer);
            sofer.setDisponibil(false);
            comanda.setStatus("In curs de livrare");
            comandaDAO.update(comanda); // UPDATE: assigned driver + status
            soferDAO.update(sofer);     // UPDATE: the driver becomes unavailable
            System.out.println("Soferul " + sofer.getNume() + " a preluat comanda #" + comanda.getId());
        } else {
            System.out.println("Comanda #" + comanda.getId() + " este in asteptare. Niciun sofer disponibil!");
        }
        audit.logActiune("alocaSofer");
    }

    public void finalizeazaComanda(Comanda comanda) {
        comanda.setStatus("Livrata");
        comandaDAO.update(comanda); // UPDATE: final status

        // free up the assigned driver (if any) and save the availability
        Sofer sofer = comanda.getSoferAsignat();
        if (sofer != null) {
            sofer.setDisponibil(true);
            soferDAO.update(sofer);
        }
        System.out.println("Comanda #" + comanda.getId() + " a fost marcata ca Livrata.");
        audit.logActiune("finalizeazaComanda");
    }

    public void istoricComenziClient(Client client) {
        audit.logActiune("istoricComenziClient");
        System.out.println("\n--- Istoric Comenzi pentru " + client.getNume() + " ---");
        for (Comanda c : comenzi) {
            if (c.getClient().equals(client)) {
                System.out.println("Comanda #" + c.getId() + " - Status: " + c.getStatus() + " - Total: " + c.calculeazaTotal() + " RON");
            }
        }
    }

    // DAO access for the CRUD demo in Main
    public ComandaDAO getComandaDAO() { return comandaDAO; }
}
